db:
  name: "r2t"
  host: "152.70.69.6"
telegram:
  token: "6234000705:AAFGI05fqrxIWcTxPK0z7lBTAnbamU2iAz0"
  dev_chat: "-1001705755126"
  papa: "507910289"
sentry: ""
reddit:
  user_agent: "Secret:Reddit_user_agent:v01 (by any /u/redditor)"
  client_id: "client_id"
  client_secret: "client_secret"
  username: "reddit2telegram_bot"
  password: "very strong password"
cron_file: "own.cron"
pool:
  class: ThreadPoolExecutor
  size: 8
